app = "yahtzee-api-mauroccamargo"
primary_region = "ewr"   # pick something close to you

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines  = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[vm]]
    cpu_kind = "shared"
    cpus = 1
    memory = "256mb"
